### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by gilbertohasnofb** [nightflyer73/plugin.video.guardian#1]
I am having troubles with this add-on, my `kodi.log` outputs the following error:

```
23:59:33 T:140648849983232   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 0] Error>
                                            Traceback (most recent call last):
                                              File "/home/gilberto/.kodi/addons/plugin.video.guardian/default.py", line 82, in <module>
                                                show_categories()
                                              File "/home/gilberto/.kodi/addons/plugin.video.guardian/default.py", line 43, in show_categories
                                                items = gtv.getChannels()
                                              File "/home/gilberto/.kodi/addons/plugin.video.guardian/resources/lib/guardian.py", line 23, in getChannels
                                                data = urllib2.urlopen(pageUrl).read()
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 467, in error
                                                result = self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
                                                return self.parent.open(new, timeout=req.timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
                                                context=self._context)
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 0] Error>
                                            -->End of Python script error report<--
23:59:33 T:140650046548416   ERROR: GetDirectory - Error getting plugin://plugin.video.guardian/
23:59:33 T:140650046548416   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.guardian/) failed
```

**Comment by nightflyer73** [comment]
It seems you had problem loading https://www.theguardian.com/video. You should really check your side (correct time, etc).
